### ISSUE TITLE
pretty output to a file with -q

### ISSUE THREAD

**Issue by ch604** [Liamraystanley/marill#28]
i like the standard output of marill, but the log output isnt as readable when running marill headless (exact command is `/root/marill -q --log-file /marill_output.txt --domains "$(cat /marilldomains.txt)"`). any way to get standard output (save the logo) to a file without resorting to `2>&1 >filename.txt`?

**Comment by ch604** [comment]
addendum: using the stdout redirection to a file will also be hard to read from a text editor or `less` because of the color calls; stripping color out of this standard output to file would be helpful as well.

**Comment by Liamraystanley** [comment]
This should be good to go from commit d0031a486e0f71450cc69466d9c9fece2194cd6a and dbc2d494babc0fa240ecafa28eee74aac574c7b7
